

# get all posts
GET http://localhost:3000/api/posts



### get post by id
GET http://localhost:3000/api/posts/1

### get post by owner
GET http://localhost:3000/api/users/Tomer/posts



### delete post
DELETE http://localhost:3000/api/posts/1



### publish post
POST http://localhost:3000/api/posts
Content-Type: application/json

{
    "ownerId": "Tomer",
    "content": "Hello Post"
}